"""
print(pow(3,5))
print(round(3.1415926,2))
print(max(12,3,11,6,7))#min
print(divmod(16,3))
print(eval("5+5"))
"""

"""
a=int(input(""))
b=int(input(""))
c=int(input(""))
d=int(input(""))
e=int(input(""))
f=int(input(""))
j=int(input(""))
h=int(input(""))
i=int(input(""))
g=(a+b+c+d+e+f+j+h+i)
k=g-(max(a,b,c,d,e,f,j,h,i)+min(a,b,c,d,e,f,j,h,i))
print(round(k/7,2))
"""
